README.md
dev/README.md
dev/refresh-database

This is useful for refreshing our shared testing instance, but can also be used for local dev instances.  The process is intended to be robust so that we could put it on an automatic weekly or (even daily?) schedule if desired.
Command for refreshing your local dev environment is:
```
./dev/refresh-database
```
Command for refreshing the testing environment is:
```
PGHOST=testing.db.seattleflu.org PGDATABASE=testing PGUSER=postgres ./dev/refresh-database
```
If you provide a directory as the first argument, the database dump will be preserved and re-used between runs (so you can save a bunch of time and use the same dump for a week or two for local dev).

Refreshing of a target database using dumps from our production database

---

crontabs/id3c-production

Automate the upload of new manifest data by adding a new cronjob that invokes the `update-unattended` script from http://github.com/seattleflu/specimen-manifests.

Automate upload of new manifest data

---

export/science-map-geojson

We had previously set a Year 2 start date arbitrarily to September 1,
2019. Per Trevor, we want to update this start date to October 1, 2019
to "make our use of 'Y1' synonymous with the use of '2018-2019 influenza
season' by outside groups."

science-map: Update Y2 start date to Oct 01

---

metabase/README.md

Add documentation for how to restart, see service status, and view logs
with Metabase. Organize the README with new section headers.

metabase: Describe how to restart and see status

---

crontabs/id3c-production
id3c-production/logging.yaml

These were producing low-level but constant daily noise in our ETL jobs
and causing alerts.  If an alert is ignorable, like these, then the
alert shouldn't have happened in the first place.
Intentionally targeted very specifically so we don't suppress messages
about other unknown identifiers, or even these identifiers in other
(unexpected) contexts.
---
Requires seattleflu/id3c#106.

Suppress unknown identifier warnings for presence/absence control samples

---

lab-labels/lab-labels.service
metabase/metabase.service

This was the intended behaviour, but it was thwarted by using an
incorrect, non-existent target unit name (local.target).  Whoops!
Use a standard built-in target instead!
Automatically starting services after boot is important since the
backoffice will now, if necessary, automatically reboot in the middle of
the night to apply security patches.

Start Metabase and Lab Labels services at boot

---

export/science-map-geojson

Update the export script for the science map to use the new version of
the augur build metadata view.
~This PR is dependent on https://github.com/seattleflu/id3c-customizations/pull/40 and will be kept as a draft until the original PR is merged.~

science-map: Update to augur build metadata v3

---

bin/terminate-idle-sessions
crontabs/id3c-production

Add a crontab that runs every minute to terminate idle database sessions
other than those of superusers, the `rdsadmin` and the `metabase` roles
that have been idle for more than 30 minutes.

Add routine to terminate idle database sessions

---

bin/upload-sch-retrospective-data-pulls

Amanda is not longer sending us retrospective SCH data in CSV format.
When running the automated `upload-sch-retrospective-data-pulls` script,
check for `.xls` file extensions instead of `.csv`.
-------
Depends on https://github.com/seattleflu/id3c-customizations/pull/53

upload-sch-retrospective-data-pulls: Use .xls instead of .csv

---

bin/terminate-old-metabase-sessions
crontabs/id3c-production

Add a crontab that runs every minute to terminate old metabase sessions that have been active for more than 10 minutes.
10 was an arbitrary number, we can change the interval if we need to.

Add routine to terminate old metabase sessions

---

dev/refresh-database

Avoids errors and unexpected settings within these user-specific
preference files; should be a standard thing we do for batch jobs using
psql.
For example, I recently added "\set ON_ERROR_STOP=1" to my ~/.psqlrc so
interactive psql sessions had better error-handling behaviour for
multiline inputs, but this broke refresh-database, which expected errors
to be ignored by default.

refresh-database: Prevent loading of psqlrc files

---

crontabs/id3c-production

Run 5 minutes after presence/absence results are uploaded to check
if any contain reportable conditions.

crontabs: reportable conditions

---

bin/scan-return-of-results/transform

Otherwise case-differences, to use a real observed example, will fail
the assertion.

Normalize all SCAN barcodes before assertions

---

bin/scan-return-of-results/export-redcap-scan
bin/scan-return-of-results/transform

Thinking is that we'd still want to catch mismatches for manual review
on subsequent issues.  And we can still relax the assertions further in
the future, if needed.
Masks by REDCap record id to avoid leaking the barcode itself.

Mask a known barcode mismatch in SCAN return of results processing

---

bin/scan-return-of-results/generate-pdfs
bin/scan-return-of-results/transform
crontabs/uw-lab-med-return-of-results

This is the backoffice cronjob to generate PDFs. Most of the actual PDF generation code lives in https://github.com/seattleflu/lab-result-reports.

Generate lab result report PDFs for SCAN 

---

bin/scan-return-of-results/transform

Mask 'inconclusive' results as 'pending' (similar to what we do for
positives) when a participant has not yet been contacted by study
member.

scan-return-of-results: Mask 'inconclusive' when not contacted

---

bin/scan-return-of-results/transform

"return_utm_barcode" is the barcode which is most reliable and has the
final say in the case of kit mixups.  Switching to this avoids having to
manually mask data entry or pre-shipment scanning errors.
Duplicates in this field are a mistake and should be very rare, but drop
any that are seen and issue a warning.  Manual followup with the lab
team is required in such cases.
As a result of not using the pre-shipping or participant-entered
barcodes, rows where status_code == not-received will drop out from the
SecureLink data file, which will land more people on the SecureLink SCAN
error page.  The error page already says it may not be received yet, and
I've added another PR to make it a bit better still.

SCAN: Rely only on the barcode scanned during returned kit processing

---

bin/scan-return-of-results/generate-pdfs

Generate PDFs for three additional finalized languages: Spanish,
Vietnamese, and Chinese (simplified).
Use the latest Docker image for PDF generation.

Generate PDFs for es, vi, zh-Hans

---

bin/scan-return-of-results/generate-pdfs
bin/scan-return-of-results/generate-results-csv
crontabs/id3c-production

Add traditional Chinese (zh-Hant) to the list of REDCap project
languages we iterate over to export SCAN participant results. Use the
latest Docker image build that includes traditional Chinese.

Add zh-Hant to list of languages to export

---

crontabs/id3c-production

The manifest parse/upload/ingest is often the blocker for the ingest
of presence/absence results. Increase the frequency of the manifest
jobs to avoid extended delay of results.

crontabs: increase frequency of manifest jobs

---

bin/scan-return-of-results/export-redcap-scan
bin/scan-return-of-results/generate-pdfs
bin/scan-return-of-results/generate-results-csv
bin/scan-return-of-results/transform

See commit messages for details.
I believe the barcode handling is correct and appropriately cautious, but I'm not super happy with the Pandas bits. I wonder if there's a clearer approach. Happy to hear suggestions!
This is ready for review, although there's one remaining commit/todo item before this merges:

Return of results processing for SCAN kiosk/in-person enrollments

---

id3c-production/logging.yaml
id3c-testing/logging.yaml

Filter out warnings for sample barcodes with suffix "*_exp", which is used by the lab for
experimental barcodes. These warnings are ignorable because these barcodes are not meant
to be ingested by the presence/absence and manifest ETL jobs.
https://trello.com/c/lolX0N3y/691-suppress-warning-for-barcodes-with-exp-suffix

Suppress no id warning for experimental barcodes

---

bin/scan-return-of-results/transform

A recent upgrade of Pandas caused the replacing of empty strings
(created by whitespace trimming) with NA to stop working.  This
manifested as both a FutureWarning from NumPy:
.../lib/python3.6/site-packages/pandas/core/missing.py:49:
FutureWarning: elementwise comparison failed; returning scalar instead,
but in the future will perform elementwise comparison
(a symptom of the Pandas bug) and also our own warning about large
numbers of records containing the "duplicate" empty string barcode:
Dropped 1,483 REDCap records with duplicated barcodes: ['']
This, it turns out, is a known bug in replace()¹ when called in its
two-arg form.  However, the bug didn't seem to affect the string dtype
until recently.
Strangely, the one-dict-arg form of replace() is not affected by the bug
and …

scan-return-of-results: Avoid Pandas bug when replacing empty strings with NA

---

bin/scan-return-of-results/transform

This is done to prevent the return of results from being blocked by the
lack of swab type for never tested samples. The timing of a sample
getting marked as `never-tested` in REDCap and added to the
incident report is out of our control. This may lead to a block of
results since we cannot generate a PDF report without a known swab type.
A separate query is set up on Metabase to check hourly for null swab
types so that we know when we need to manually intervene.

scan-return-of-results/transform: set null swab_type to "pending" status

---

etc/uw-retrospectives-manifest.yaml

Add configuration for the latest specimen manifests aliquoting sheet,
number 8, to the UW retrospectives manifest file.
-----------------
Depends on https://github.com/seattleflu/specimen-manifests/pull/16

Add aliquot sheet 8 to uw-retrospectives manifest

---

crontabs/id3c-production

Explicitly run it in our id3c-production environment instead of relying
on specimen-manifests to know the layout and location of backoffice.git.
Requires 087cba2 in specimen-manifests from the no-pipenv branch and PR
17 <https://github.com/seattleflu/specimen-manifests/pull/17>.

crontabs: Run specimen-manifests/update-unattended under pipenv

---

bin/return-of-results/generate-pdfs

Bump the Docker tag used to generate PDFs so we're making PDFs with the
latest template that uses SFS branding instead of SCAN.
This should be merged in sync with the rebranded SecureLink site going live.

return-of-results: Bump Docker tag for PDFs

---

bin/uw-ehs-report/transform

There is an issue importing records that have
uw_dorm_room_number populated. This is temporary removal
until we can fix the field.

Omit the uw_dorm_room_number field

---

bin/uw-ehs-report/export-redcap-uw-reopening
bin/uw-ehs-report/transform

Replacing a placeholder NA value with the actual computed value for symptomatic_when_tested.
The ETL does not ingest the questionnaire items from the two instruments where these fields are, so I'm pulling directly from REDCap.

uw-ehs-report: Populate symptomatic_when_tested

---

web/index.html

Link to the new /husky-musher/lead-dawgs app for streamlining kiosk
testing for UW Reopening.
Depends on https://github.com/seattleflu/husky-musher/pull/4

web: Add link to Lead Dawgs app

---

bin/return-of-results/export-redcap-sfs-longitudinal
bin/return-of-results/export-redcap-uw-reopening
bin/return-of-results/generate-results-csv
bin/return-of-results/transform
etc/sfs-longitudinal-redcap-projects.yaml

* Generalize the UW-reopening REDCap export script to export any SFS longitudinal REDCap project that is defined in the `etc/sfs-longitudinal-redcap-projects.yaml` config file.
* Update the ROR transform script to required contacted field for SFS Childcare studies
* Check for duplicate barcodes across __all__ studies instead of just within each study arm.

Add SFS Childcare to ROR

---

bin/mint-barcodes-in-batch

Adjust the call to subprocess.run() to work on python 3.6.
Also display the stdout from the calls so we can see how many
retries were required.

Fix subprocess call for barcodes script

---

id3c-production/env.d/aliquot-manifest-processing/CONFIG
id3c-production/env.d/aliquot-manifest-processing/MANIFEST

Update the `update-unattended` specimen manifests cron job environment
variables to pull from the new, season 3 manifest sheet.
Note that the lab does not anticipate updating the season 2 manifest save any barcode corrections. If these arise, the plan is to handle them manually.
Depends on https://github.com/seattleflu/specimen-manifests/pull/22

Update to season 3 manifest

---

bin/promjob
crontabs/id3c-production
crontabs/return-of-results
crontabs/scan-switchboard
crontabs/uw-ehs-report

Adds a new exec-chaining command, "promjob", which writes metrics (start
time, end time, duration, exit status) to Prometheus' node_exporter's
textfile collector directory.  These metrics will let us monitor (and
alert, if we wish) on the status of our jobs.
Notably, promjob will still work nicely if/when we move from cronjobs to
systemd timers (as I increasingly thing we should do) or even other
scheduled task systems.  In the case of systemd, invocations can re-use
the systemd unit name via interpolation, e.g. `promjob %N …`.
Another way to think about this same information would be via an
event-log mindset, where the cron logs (e.g. in /var/log/syslog) are
piped into an event-log store (e.g. ELK stack or CloudWatch) from which
these metrics are then computed.  This has some advantages, …

Export basic cronjob metrics to Prometheus

---

crontabs/id3c-production

To be deployed in coordination with https://github.com/seattleflu/id3c/pull/180.
Bumps the frequency of the UW Reopening REDCap DET ETL to once every 10 minutes.

Configurable cache

---

id3c-production/logging.yaml
id3c-testing/logging.yaml

Update our logging configuration to silence yet another test sample that
isn't meant to end up in id3c.

Silence alerts for Hap1 and exp samples

---

crontabs/id3c-production

As I noted as comments in the cron file, run this job at :15 and :45 after the hour.
redcap-det uw-reopening runs at  /10
etl fhir runs at /5
refresh-materialized-view shipping fhir_questionnaire_responses_v1 runs at /5
The offer job uses data from all 3 of those other jobs. Run this at :15 to use the :00 redcap-det uw-reopening run and at :45 to use the :30 redcap-det uw-reopening run.
Space the two runs out to give the other jobs a few times to run between.

Add cronjob for uw reopening offers

---

bin/uw-ehs-report/import-to-uw-ehs-transfer-redcap

Import Husky Coronavirus Testing data into the EHS REDCap transfer
project in batches of 10,000 records. Uploading the full dataset
(currently 24k records) was causing the import into REDCap to fail.

Import HCT data to EHS REDCap in batches

---

bin/uw-ehs-report/transform

Before import data into the EH&S HCT transfer project, drop duplicate
barcodes from the dataset.

id3c-production: drop duplicate HCT barcodes for EHS transfer

---

bin/uw-ehs-report/transform

During transfer of HCT results to EHS, now that we are
outputting the message for duplicates values in the ID3C
dataset as well as REDCap, make the message non-specific to
REDCap.

id3c-production: clarify duplicate message in EHS transform

---

bin/return-of-results/generate-results-csv

Exit the return-of-results (RoR) job if the CSV export from id3c fails
(e.g. because the database is unavailable). Previously, we were not
killing the RoR job on a failed `export-id3c-return-results` command due
to our use of process substitution. I.e., as @tsibley pointed out, "when
`command` fails in `<(command)`, it doesn't propagate."
Explicitly kill the current PID when our id3c export command exits with
a non-zero exit code. This halts the entire RoR job, preventing us from
unintentionally uploading an empty CSV and overrwriting the
(unversioned) data on securelink's S3 bucket with an empty file. This
happened last month, causing the RoR job to regenerate PDFs for every
single result, which at our current program's pace, would have taken
multiple days to complete.

return-of-results: Exit if id3c export fails

---

bin/fatigue
crontabs/return-of-results
crontabs/uw-ehs-report

Previously, fatigue only specially handled suppressing repeated warnings
of jobs that exit with an error. Modify fatigue to also suppress jobs
with any sterr output. Sterr output is generated at the "warning" and
"error" log levels, so this will reduce the warnings alert spam we
receive via email and in the #id3c-alerts channel.

fatigue: Modify to suppress multiple, repeated warnings

---

bin/generate-and-upload-uw-retro-redcap-dets

This works as-is now but importantly ensures forward-compatibility with
upcoming changes in ID3C to use the new-style env var names.¹  Deploying
this in advance of those changes will result in no disruption.
¹ https://github.com/seattleflu/id3c/pull/197

Explicitly specify the name of token env var for UW retros REDCap DET generation

---

dev/refresh-database

Remove comments on extensions from the TOC when refreshing a target
database with a copy of the production database.
@tsibley pointed out that comments on extensions require a true
superuser, but RDS doesn't offer us that. Therefore, filter out comments
on extensions while preserving other comments (instead of using the
nuclear `--no-comment` option available in Postgres 11).

refresh-database: Exclude comments on extensions

---

crontabs/id3c-production

Please see notes in the commit messages. 
1. Use flock for refresh materialized view jobs.
2. Run the refresh materialized view jobs less frequently.
3. Reduce the UW Reopening ETL's redcap-api-batch-size.
Before deploying this, create a flock directory on the backoffice server:
/home/ubuntu/flock .

Cron job adjustments

---

crontabs/scan-switchboard
scan-switchboard/scan-switchboard.service

See https://github.com/seattleflu/scan-switchboard/pull/28.

switchboard: Adjust deployment to use the pip-tools venv instead of Pipenv

---

bin/uw-ehs-report/generate
bin/uw-ehs-report/generate-report
bin/uw-ehs-report/import-to-uw-ehs-transfer-redcap
bin/uw-ehs-report/transform
id3c-production/Pipfile.lock

Motivated by the problems with the UW EH&S report yesterday.
See commit messages for details.
Todo:

uw-ehs-report: Use NDJSON instead of CSV for the intermediate file format

---

id3c-production/logging.yaml
id3c-testing/logging.yaml

Update logging configuration to suppress alerts for more test samples.
We don't need to see these warnings because these samples are not
supposed to be ingested into ID3C.

Suppress alerts for Hap1 Testing Samples

---

crontabs/id3c-production

We went the entire day without noticing that the presence-absence ETL
had been failing since last night. In this case I would rather see
Slack alert entries every 15 minutes than to go a day without seeing
a problem with our results release pipeline.

Stop silencing errors from the presence-absence ETL

---

bin/return-of-results/export-redcap-sfs-classic
bin/return-of-results/generate-pdfs
bin/return-of-results/generate-results-csv
bin/return-of-results/transform
crontabs/return-of-results
etc/sfs-classic-redcap-projects.yaml

For the AFH/Workplace project we needed a new code path to handle "classic" REDCap projects that don't follow all the rules of SCAN (doesn't require contacting the participant before releasing a positive or inconclusive result). I used the idea done with the longitudinal path to create a config-driven classic path.
When generating PDFs, we now generate a PDF in all languages for "IRB" results and use a different template for English "clinical" results.
This depends on the corresponding template changes in https://github.com/seattleflu/lab-result-reports/pull/28/files

Accommodate afh

---

crontabs/id3c-production
crontabs/return-of-results
crontabs/scan-switchboard
crontabs/uw-ehs-report

Fatigue masks failed exit statuses as part of its collab with chronic,
which means that promjob reports jobs as exiting with success when
fatigue was suppressing a repeated error.  This is unhelpful behaviour
for metrics and monitoring!, so move promjob after fatigue so it can see
real exit statuses.  If chronic and fatigue are paired, they are kept
together.  Uses of chronic sans fatigue were left alone, as chronic does
not modify exit statuses without -e, which we don't use.
I'd originally made promjob the very outer layer in the exec chain so
that it reported on the entire job, not just some inner piece of it, and
I think still a good practice to place it as left-most as reasonable.
In any case, we still expect to ditch fatigue once our alerting from
metrics and logs is better.

crontabs: Move promjob after fatigue

---

bin/return-of-results/transform

My original statement about appending DataFrames that have different
columns was incorrect. The values in the disconcordant columns will be
`NA` for a string column (and `NAN` for other types). There's no need
to replace data after the append. In fact, the `replace` line was
causing this warning:
`FutureWarning: elementwise comparison failed; returning scalar instead,
but in the future will perform elementwise comparison`
Also, the .append() method can take a list of DataFrames to append. It's
more efficient to append the two in the same command.

Remove bad assumption and combine append commands

---

bin/wa-doh-linelists/transform
etc/wa-doh-linelists.yaml

I was using the id3c-customizations `zipcode_map()` function to convert
REDCap raw zipcode labels to their real zipcode equivalent. However, HCT
zipcodes (at least in the EH&S project) are already the real zipcode. I
overlooked the fact that the `zipcode_map()` function returns None if
the input data don't exist in the map. This commit preserves the
original zipcode if no appropriate mapping was found (rather than
overwriting it with None).

wa-doh-linelists: Fix HCT zipcode

---

bin/wa-doh-linelists/transform

Exit with a helpful message when duplicated barcodes are found in REDCap when creating the WA DOH Linelist export.

Linelist merge error

---

bin/return-of-results/export-redcap-sfs-classic
bin/return-of-results/export-redcap-sfs-longitudinal
bin/return-of-results/transform
etc/sfs-longitudinal-redcap-projects.yaml

The bulk of this PR is adding field mapping and barcode prioritization logic to the SFS longitudinal configuration driven parser to match what was put in for the classic mode. This accommodates REDCap projects that use fields that aren't named like other projects and explicitly configures whether the project requires contact the participant before releasing positive results.
A commit fixes two small bugs in the classic mode.
A commit adds longitudinal configuration for the Apple Respiratory Study.
For testing, I ran `generate-results-csv` using this version of the code and right after using the master version of the code. A diff revealed no differences.

Add longitudinal mapping

---

crontabs/id3c-production

The childcare project is transitioning from the pilot to a 2021 version.
Update the id3c-production cron tab to replace exisiting with the new
etl command. The command name change is because its a different project, 
and the existing etl command is left in place to be run manually if needed.

Update crontab to run childcare etl for 2021 project

---

bin/redcap-data-dictionary/download-data-dictionary
bin/redcap-data-dictionary/upload-data-dictionary

In a new ID3C PR (209), we change the `redcap.metadata` and
`redcap.update_metadata` methods to use the term "fields" instead of
"metadata". Update the backoffice code accordingly.
-------------
Depends on https://github.com/seattleflu/id3c/pull/209

redcap-data-dictionary: Rename id3c.cli methods

---

bin/return-of-results/transform

The code needs to handle the case where the config driven
classic or longitudinal REDCap project fetch returns no records.
When processing the output of the fetch, check if the DataFrame
created from loading the data has rows, and if not, return None
instead of trying to transform that DataFrame.

Handle empty REDCap recordsets in config driven RoR

---

bin/return-of-results/generate-results-csv

Handle all process substitutions similarly, instructing the child
process to kill the parent in case it fails. This introduces a race
condition where the parent process will no longer be around for the non-
winning processes.
------------------------------
Addresses post-merge feedback from https://github.com/seattleflu/backoffice/pull/111.

generate-results-csv: Kill all failed processes

---

crontabs/scan-switchboard

From the old NDJSON file to the new CSV file.  Makes no difference with
regards to locking behaviour, but avoids keeping the NDJSON file around.

crontabs: Update lockfile for Switchboard update

---

bin/refresh-materialized-shipping-views
crontabs/id3c-production

The `__uw_encounters` and `scan_encounters_v1` materialized views depend
on the `fhir_questionnaire_responses_v1` materialized view.
This commit adds a new script that refreshes the materialized shipping
views in the correct order and updates the production crontab to
run this script instead of refreshing the materialized views
individually.
Currently, it takes about 10 minutes to materialize the 3 views in
production. Therefore, the refresh job is configured to run every 30
minutes. The start times of the `UW Reopening testing offers` job have
been pushed back to allow the materialized views refresh to take
up to 25 minutes.

Wrap refresh materialized view jobs into one job

---

etc/sfs-longitudinal-redcap-projects.yaml

Do not deploy this change until the 2 REDCap projects have been put into production mode. They were copied with real records from the English project.

Add RoR config for Snohomish Schools translations

---

crontabs/id3c-production

The backoffice server is configured to reboot at 4 AM if it needs to
in order to install patches. For jobs that run only once a day at 4 AM,
run them at 5 AM instead to avoid getting skipped while the machine is
restarting.

production crontab: run at 5 AM instead of 4 AM

---

bin/uw-ehs-report/generate-report
bin/uw-ehs-report/transform

Previously, the entire output file from the REDCap dump was loaded
at once. This was causing out of memory errors, as the working memory
grew past 9 GB. In this commit, the REDCap file is read in chunks and
the content of each chunk is processed completely as one batch. Peak
memory consumption as configured is around 3.5 GB.
The original `transform` script took about 51 seconds to process today's
data. This new version took slighly longer at 63 seconds.
I've tested by comparing the output generated by the master version of `transform` against this new version. There are no differences in the output.

Process REDCap data in chunks for the EH&S Transfer

---

etc/uw-retrospectives-manifest.yaml

Lab is rolling over to aliquot manifest sheet 11, so start ingesting.

Update UW retrospective manifest config with aliquot sheet 11

---

bin/upload-sch-retrospective-data-pulls

The latest uploads of SCH metadata include files with year 2021.
Add 2021 to the glob pattern for AWS files to include the latest files.

SCH retro pulls

---

bin/wa-doh-linelists/generate
bin/wa-doh-linelists/transform
crontabs/id3c-production

Use cron to generate daily linelists and upload to S3. Study staff can
then download the file from S3 to distribute to partner agencies,
instead of having to generate it locally.
This lets us control the environment for linelist generation and
simplifies the process for study staff. Eventually, it'd be great to
automatically upload the linelists directly to the partner agencies.

Automate linelist generation and upload to S3

---

bin/terminate-slow-metabase-queries

Otherwise some of these routine queries are not completing for very
field/value enumerations of very large and slow views.  We will
additionally reduce their cadence so they don't run as often.
Queries that are run on behalf of a user have an extended remark comment
at the beginning of the query indicating as much.¹  Positively select
for these to allow any non-user driven queries through.
¹ https://github.com/metabase/metabase/blob/b8c81d0277c509f37ade13a764eef5dc42a06fb6/src/metabase/query_processor/util.clj#L26-L37

Exclude queries run by Metabase for sync/scan introspection from the slow-query killer

---

crontabs/id3c-production

Suppresses noisy informational output unless the job fails.

crontabs: Run WA DOH linelist reporting job under chronic

---

crontabs/id3c-production

Due to other issues, we fell behind in our typical processing of UW
re-opening/ HCT records. As such, we were processing closer to the
prior det limit of 1000 dets at a time, and were seeing OOM on the
host trying to process that many records at once. Typically, this
job had been running far below the set limit of 1000. Let's reduce
the job to process a max of 500 redcap DETs at a time.
Note: This should not be deployed before https://github.com/seattleflu/id3c/pull/232.
Backoffice production is currently intentionally rolled back a few commits behind master, and 
we should wait for the new pinning id3c's click dependency before deploying this branch to 
backoffice to keep the state of prod clean.

Reduce det-limit for UW Reopening ETL to 500 records

---

crontabs/id3c-production

We are again getting 500 responses again from Redcap's API when we try
to pull records, using 75 records at a time for the HCT project.
I reproduced locally and then reduced to 60 and saw successful responses
from the Redcap API.

crontabs: Reduce HCT Redcap API batch size from 75 to 60

---

bin/export-prevalence
crontabs/Makefile
crontabs/public-datasets

This data file will power a chart of pathogen prevalence on
seattleflu.org.
The s3://seattle-flu-study bucket existed already and was previously
used for the samples.geojson file powering the heat map on
seattleflu.org.  I updated the backoffice-automation IAM group to allow
PUTs to this new file and also setup a CloudFront distribution for the
bucket served at https://data.seattleflu.org.

Publish weekly pathogen prevalence data every day

---

bin/upload-prevalence
crontabs/public-datasets

Oops, we want to capture metrics on all jobs!  This was an oversight on
my part.  (Another good reason to switch to systemd timers, where we can
more automatically and ~transparently capture these metrics.)

Run pathogen prevalence job under promjob

---

bin/import-uw-retrospectives-to-redcap

The lab does not currently record MRN and accession during specimen
intake, but the plan is to start soon.

Include residuals from PHSKC in our UW EHR data requests

---

bin/export-prevalence

Rolls up our broader Enterovirus targets plus Enterovirus.D.68 into a
single count.

export-prevalence: Add Enteroviruses to the data

---

.github/workflows/shellcheck.yml
.shellcheckrc
bin/fatigue
bin/generate-and-upload-uw-retro-redcap-dets
bin/import-uw-retrospectives-to-redcap
bin/promjob
bin/refresh-materialized-shipping-views
bin/upload-prevalence
bin/upload-sch-retrospective-data-pulls
bin/uw-ehs-report/generate
bin/wa-doh-linelists/export-id3c-hcov19-results
bin/wa-doh-linelists/generate
dev/README.md
dev/refresh-database
dev/shellcheck

Helps identify and avoid common shell pitfalls. Addresses all issues reported.

Run Shellcheck on every push as part of CI

---

bin/refresh-materialized-shipping-views

The extra leading space in front of `__uw_encounters` started causing
errors due to the bash variable syntax change
in 74c8ead1a27bfa386148ab63d2e3dfb1b71b57a6.

refresh-materialized-shipping-views: delete extra leading space

---

bin/import-uw-retrospectives-to-redcap

jq was throwing error messages about not being able to test() the
.sample_origin when it is null.

Quiet down the UW retros import

---

bin/return-of-results/export-redcap-scan
bin/return-of-results/export-redcap-sfs-classic
bin/return-of-results/export-redcap-sfs-longitudinal

Use the ID3C Redcap page_size param to fetch records in pages
instead of all at once for each Redcap project.
Fetching all the records at once was causing us to get 500 responses
on these requests with a message that "REDCap ran out of server memory"
responses from Redcap.
I'll start by setting page_size to 5000 for all the projects, which is
what we are currently using to fetch from HCT. We may need to tune it
later. This succeeded at the time of testing, but we will find out more
tonight, because we have more frequently been seeing the Redcap API
memory-related errors outside of business hours.

return-of-results: use pagesize when fetching redcap records

---

bin/terminate-idle-sessions

This is the database "root" user, and should be excluded just like
"rdsadmin". We use "postgres" for `sqitch deploy`, which seems like it
can end up idle (or idle in a transaction) while it waits on a lock.

terminate-idle-sessions: Exclude postgres user from consideration

---

etc/uw-retrospectives-manifest.yaml

Adds aliquot sheet 15 to the list of worksheets for ingestion. Aliquot sheet 15
is the first and likely only worksheet that will be generated directly
from LIMS as an interim solution until we have an API developed accepting data in
real time.
This YAML file also switches to the new simplified format where multiple worksheets
sharing the same format can be entered as a list of values.

etc/uw-retrospective-manifest: add aliquot sheet 15

---

wa-doh-linelists/Pipfile
wa-doh-linelists/Pipfile.lock

s3fs 2021.06.1 doesn't seem to respect the AWS_DEFAULT_REGION environment variable, but it works in 0.4.2.
```
$ env|grep AWS
AWS_DEFAULT_REGION=us-west-2
$ pip list | grep s3fs
s3fs              2021.6.1
$ echo "import fsspec; fs=fsspec.open('s3://testing-bucket/afilethatexists.txt', mode='w')" | python3; echo $?
PermissionError: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.
1
$ pip list | grep s3fs
s3fs              0.4.2
$ echo "import fsspec; fs=fsspec.open('s3://testing-bucket/afilethatexists.txt', mode='w')" | python3; echo $?
0```

Downgrade s3fs to 0.4.2 to fix linelist upload

---

dev/populate-test-quota-sql.txt

Continuation of 256f4e600cf46e00b2f6aac016d26ef652644381 to handle hourly intevals > 1
and cases where daily quota is less than the number of iterations generated by number of hours
divided by the hourly interval, both which could cause the total number of hourly quotas
inserted in any given day to be higher than the number being requested.

Update to populate-test-quota-sql to handle any input values

---

bin/wa-doh-linelists/transform
crontabs/wa-doh-linelists

Add SSH username & private key file to wa-doh-linelist crontab for
automated file upload to the state Department of Health. It was
previously manually entered for testing; now that we've got it
working, it can go in version control.
The full path to the key is specified because cron doesn't seem to
expand $HOME, causing errors.

Add SSH creds to linelist crontab

---

id3c-production/logging.yaml
id3c-testing/logging.yaml

Update logging filters that suppress warnings for experimental
samples, to account for both a new barcode pattern from the lab,
to use the suffix _HAP1_2, and an updated log message from id3c,
to include additional information when we suppress the unknown
barcode warnings for experimental samples.
Previously updated logging pattern:
https://github.com/seattleflu/id3c/commit/11c2abb63ac08264a335bac4ca0aa837d95161e7

Re-suppress alerts for experimental samples
