id3c-production/env.d/uwsgi/LOG_CONFIG, id3c-restricted/env.d/uwsgi/LOG_CONFIG
Makes sure that syslog messages from them are handled the same way.
=> Use our custom logging configs for our API servers running under uWSGI

id3c-production/logging.yaml, id3c-testing/logging.yaml
Adds matches for:
PTC_*
*_HAP1
Water_Control
all of which are names given to various control samples.
=> Logging filters

bin/scan-return-of-results/generate, bin/scan-return-of-results/generate-pdfs
Generate SCAN results PDFs only for new or changed data.
=> Optimize pdf gen

etc/uw-retrospectives-manifest.yaml
The lab has now concluded aliquoting sheet 5 for season two. Start
ingesting sheet 6.
=> Ingest specimen manifest sheet 6

web/index.html
Add a new card to http://backoffice.seattleflu.org that points to the
new SCAN Switchboard application.
=> web: Add card for SCAN Switchboard

bin/fatigue, crontabs/id3c-production, crontabs/scan-amazon-addresses, crontabs/scan-return-of-results, crontabs/scan-switchboard
See commit messages. I think this should stop floods of cron errors.
=> Notification fatigue

etc/uw-retrospectives-manifest.yaml
Start ingesting aliquoting sheet 7. This includes new columns `swab_type` and `collection_matrix`.
https://trello.com/c/XjWs7Yji/677-update-specimen-manifest-ingest-to-put-swab-type-and-media-into-warehousesampledetails
=> Ingest specimen manifest sheet 7

crontabs/id3c-production
Should be deployed with https://github.com/seattleflu/id3c-customizations/pull/129
=> crontabs: Refresh materialized view shipping.scan_encounters_v1

etc/uw-retrospectives-manifest.yaml
Deploy when the manifest-9 has been uploaded to AWS.
=> Manifest-9

crontabs/id3c-production
Depends on https://github.com/seattleflu/id3c-customizations/pull/143
=> crontabs: Add UW Re-opening ETL

bin/return-of-results/export-redcap-uw-reopening, bin/return-of-results/generate-results-csv, bin/return-of-results/transform, crontabs/return-of-results, id3c-production/env.d/redcap-sfs/.gitignore, id3c-production/env.d/redcap-sfs/REDCAP_API_URL
Add UW Reopening REDcap project to return of results pipeline.
=> UW Re-opening ROR

etc/uw-retrospectives-manifest.yaml
Add sheet 10 to the uw-retrospectives-manifest config file.
=> Add specimen manifest sheet 10

etc/uw-retrospectives-manifest.yaml
Forgot to update this config when we transitioned to the new season
3 manifests.
=> Update UW retrospecive manifest config with season 3 manifests

crontabs/scan-switchboard
These are a couple of small changes to make updating the Switchboard a bit smoother.
=> Switchboard enhancement

crontabs/id3c-production
Do not deploy until corresponding ID3C customizations are deployed.
That is https://github.com/seattleflu/id3c-customizations/pull/174
=> Add cron job to refresh uw materialized view

bin/wa-doh-linelists/transform, etc/wa-doh-linelists.yaml
This PR addresses the formatting issues Misja recently raised in Slack regarding the new linelists we submit to WA DoH.
=> Linelist formatting

bin/return-of-results/transform, etc/sfs-longitudinal-redcap-projects.yaml
Both projects are longitudinal. Both projects require contacting the participant before releasing a positive result to the portal.
=> Add two studies to Return of Results

scan-switchboard/scan-switchboard.service
Relies on https://github.com/seattleflu/scan-switchboard/pull/38.
=> Switchboard: Change invocation to account for Datasette upgrade

etc/sfs-longitudinal-redcap-projects.yaml
Holding off on deploying this until the redcap project is transitioned to production.
=> etc: Add Yakima Schools project to Return of Results config

bin/wa-doh-linelists/transform
Fix a bug with s3 protocol specification introduced because of differences in the way I tested locally.
=> Fix s3 protocol specification

husky-musher/uwsgi.ini, id3c-production/uwsgi.ini, id3c-testing/uwsgi.ini
See related changes in our seattleflu/infra repo.
https://github.com/seattleflu/infra/pull/8
=> Adjust uWSGI config files for the multi-app service → single-app services switch
